### PR TITLE
Code formatting

### PR DESCRIPTION
**Pull request by graeme-a-stewart**
Use code formatting with the setup:

```toml
style = "sciml"
yas_style_nesting = true
```

Source files are reformatted and a GitHub action is added

### CODE REVIEW

**Review by Moelf — APPROVED** [review]

**Comment by Moelf** [comment]
This is the expected behavior or the format CI right?

**Comment by graeme-a-stewart** [comment]
> This is the expected behavior of the format CI right?

Yes, when there is a file that's badly formatted - though the error message isn't super helpful, right?

Anyway, fixed the last file and let's retry...

**Comment by Moelf** [comment]
I thought https://github.com/julia-actions/julia-format would give you inline comment or something

**Comment by graeme-a-stewart** [comment]
It seems the workflow suggestion is to pipe this into https://github.com/reviewdog/reviewdog, which will then make a suggestion on the PR

**Pull request merged**
